from __future__ import annotations

from pathlib import Path

from .benchmarks import get_scenario


def scaffold_controller(*, path: Path, scenario: str, force: bool = False) -> dict[str, object]:
    scenario_def = get_scenario(scenario)
    target = path if path.is_absolute() else (Path.cwd() / path).resolve()
    if target.exists() and not force:
        raise FileExistsError(f"Refusing to overwrite existing file: {target}")
    target.parent.mkdir(parents=True, exist_ok=True)

    source = scenario_def.controller.read_text(encoding="utf-8")
    banner = [
        '"""Generated by webots-kit controller scaffold.',
        "",
        f"Scenario: {scenario_def.name}",
        f"Based on bundled reference controller: {scenario_def.controller.name}",
        "",
        "This file is intentionally valid as-is so it can be used as a starting point",
        "for custom controller development and `webots-kit controller validate` checks.",
        '"""',
        "",
    ]
    target.write_text("\n".join(banner) + source, encoding="utf-8")
    return {
        "path": str(target),
        "scenario": scenario_def.name,
        "source_controller": str(scenario_def.controller),
        "default_camera": scenario_def.default_camera,
    }
